//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { CustomersEntity } from './db/Customers.entity';
import { InventoryEntity } from './db/Inventory.entity';
import { ProductsEntity } from './db/Products.entity';
import { ProductCategoriesEntity } from './db/ProductCategories.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { ShoppingCartEntity } from './db/ShoppingCart.entity';
import { OrdersEntity } from './db/Orders.entity';
import { OrderDetailsEntity } from './db/OrderDetails.entity';
import { PaymentsEntity } from './db/Payments.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      VendorsEntity,
      CustomersEntity,
      InventoryEntity,
      ProductsEntity,
      ProductCategoriesEntity,
      DiscountsEntity,
      ShoppingCartEntity,
      OrdersEntity,
      OrderDetailsEntity,
      PaymentsEntity,
      ReviewsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          username: 'username 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 58,
        },
        {
          username: 'username 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 4,
        },
        {
          username: 'username 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 20,
        },
        {
          username: 'username 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 50,
        },
        {
          username: 'username 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 27,
        },
      ],
      Vendors: [
        {
          companyName: 'companyName 1',
          contactName: 'contactName 1',
          email: 'email 1',
          password: 'password 1',
          id: 46,
        },
        {
          companyName: 'companyName 2',
          contactName: 'contactName 2',
          email: 'email 2',
          password: 'password 2',
          id: 17,
        },
        {
          companyName: 'companyName 3',
          contactName: 'contactName 3',
          email: 'email 3',
          password: 'password 3',
          id: 12,
        },
        {
          companyName: 'companyName 4',
          contactName: 'contactName 4',
          email: 'email 4',
          password: 'password 4',
          id: 53,
        },
        {
          companyName: 'companyName 5',
          contactName: 'contactName 5',
          email: 'email 5',
          password: 'password 5',
          id: 54,
        },
      ],
      Customers: [
        {
          customerName: 'customerName 1',
          email: 'email 1',
          password: 'password 1',
          billingAddress: 'billingAddress 1',
          shippingAddress: 'shippingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 63,
        },
        {
          customerName: 'customerName 2',
          email: 'email 2',
          password: 'password 2',
          billingAddress: 'billingAddress 2',
          shippingAddress: 'shippingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 7,
        },
        {
          customerName: 'customerName 3',
          email: 'email 3',
          password: 'password 3',
          billingAddress: 'billingAddress 3',
          shippingAddress: 'shippingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 85,
        },
        {
          customerName: 'customerName 4',
          email: 'email 4',
          password: 'password 4',
          billingAddress: 'billingAddress 4',
          shippingAddress: 'shippingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 55,
        },
        {
          customerName: 'customerName 5',
          email: 'email 5',
          password: 'password 5',
          billingAddress: 'billingAddress 5',
          shippingAddress: 'shippingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 73,
        },
      ],
      Inventory: [
        { product: 1, quantity: 1, lowStockThreshold: 1, id: 99 },
        { product: 2, quantity: 2, lowStockThreshold: 2, id: 74 },
        { product: 3, quantity: 3, lowStockThreshold: 3, id: 92 },
        { product: 4, quantity: 4, lowStockThreshold: 4, id: 96 },
        { product: 5, quantity: 5, lowStockThreshold: 5, id: 98 },
      ],
      Products: [
        {
          productName: 'productName 1',
          vendor: 1,
          price: 0.3,
          weight: 0.26,
          description: 'description 1',
          thumbnail: 'thumbnail 1',
          image: 'image 1',
          category: 1,
          creationDate: '2025-03-09T11:21:40.888Z',
          stock: 1,
          id: 38,
        },
        {
          productName: 'productName 2',
          vendor: 2,
          price: 0.85,
          weight: 0.21,
          description: 'description 2',
          thumbnail: 'thumbnail 2',
          image: 'image 2',
          category: 2,
          creationDate: '2023-10-29T09:54:31.399Z',
          stock: 2,
          id: 15,
        },
        {
          productName: 'productName 3',
          vendor: 3,
          price: 0.18,
          weight: 0.77,
          description: 'description 3',
          thumbnail: 'thumbnail 3',
          image: 'image 3',
          category: 3,
          creationDate: '2024-10-15T06:04:08.937Z',
          stock: 3,
          id: 30,
        },
        {
          productName: 'productName 4',
          vendor: 4,
          price: 0.08,
          weight: 0.62,
          description: 'description 4',
          thumbnail: 'thumbnail 4',
          image: 'image 4',
          category: 4,
          creationDate: '2025-04-18T23:44:34.867Z',
          stock: 4,
          id: 19,
        },
        {
          productName: 'productName 5',
          vendor: 5,
          price: 0.76,
          weight: 0.24,
          description: 'description 5',
          thumbnail: 'thumbnail 5',
          image: 'image 5',
          category: 5,
          creationDate: '2024-07-09T20:49:39.119Z',
          stock: 5,
          id: 86,
        },
      ],
      ProductCategories: [
        { category: 'category 1', id: 12 },
        { category: 'category 2', id: 84 },
        { category: 'category 3', id: 53 },
        { category: 'category 4', id: 18 },
        { category: 'category 5', id: 34 },
      ],
      Discounts: [
        {
          product: 1,
          discountType: 'discountType 1',
          description: 'description 1',
          discountAmount: 0.69,
          discountPercent: 0.74,
          id: 54,
        },
        {
          product: 2,
          discountType: 'discountType 2',
          description: 'description 2',
          discountAmount: 0.39,
          discountPercent: 0.79,
          id: 39,
        },
        {
          product: 3,
          discountType: 'discountType 3',
          description: 'description 3',
          discountAmount: 0.16,
          discountPercent: 0.02,
          id: 22,
        },
        {
          product: 4,
          discountType: 'discountType 4',
          description: 'description 4',
          discountAmount: 0.34,
          discountPercent: 0.81,
          id: 86,
        },
        {
          product: 5,
          discountType: 'discountType 5',
          description: 'description 5',
          discountAmount: 0.96,
          discountPercent: 0.1,
          id: 53,
        },
      ],
      ShoppingCart: [
        { customer: 1, product: 1, priceAtPurchase: 0.26, quantity: 1, id: 50 },
        { customer: 2, product: 2, priceAtPurchase: 0.76, quantity: 2, id: 11 },
        { customer: 3, product: 3, priceAtPurchase: 0.33, quantity: 3, id: 9 },
        { customer: 4, product: 4, priceAtPurchase: 0.17, quantity: 4, id: 99 },
        { customer: 5, product: 5, priceAtPurchase: 0.22, quantity: 5, id: 92 },
      ],
      Orders: [
        {
          orderNumber: 'orderNumber 1',
          customer: 1,
          totalAmount: 0.75,
          vat: 0.74,
          totalAmountWithVat: 0.84,
          shippingCost: 0.62,
          shippingAddress: 'shippingAddress 1',
          orderAddress: 'orderAddress 1',
          orderEmail: 'orderEmail 1',
          orderDate: '2023-06-24T06:37:47.346Z',
          orderStatus: 'orderStatus 1',
          trackingNo: 'trackingNo 1',
          id: 27,
        },
        {
          orderNumber: 'orderNumber 2',
          customer: 2,
          totalAmount: 0.75,
          vat: 0.98,
          totalAmountWithVat: 0.77,
          shippingCost: 0.08,
          shippingAddress: 'shippingAddress 2',
          orderAddress: 'orderAddress 2',
          orderEmail: 'orderEmail 2',
          orderDate: '2023-08-31T02:54:55.461Z',
          orderStatus: 'orderStatus 2',
          trackingNo: 'trackingNo 2',
          id: 19,
        },
        {
          orderNumber: 'orderNumber 3',
          customer: 3,
          totalAmount: 0.92,
          vat: 0.69,
          totalAmountWithVat: 0.95,
          shippingCost: 0.3,
          shippingAddress: 'shippingAddress 3',
          orderAddress: 'orderAddress 3',
          orderEmail: 'orderEmail 3',
          orderDate: '2024-01-28T00:38:51.113Z',
          orderStatus: 'orderStatus 3',
          trackingNo: 'trackingNo 3',
          id: 1,
        },
        {
          orderNumber: 'orderNumber 4',
          customer: 4,
          totalAmount: 0.69,
          vat: 0.03,
          totalAmountWithVat: 0.83,
          shippingCost: 0.1,
          shippingAddress: 'shippingAddress 4',
          orderAddress: 'orderAddress 4',
          orderEmail: 'orderEmail 4',
          orderDate: '2024-02-05T09:07:41.692Z',
          orderStatus: 'orderStatus 4',
          trackingNo: 'trackingNo 4',
          id: 54,
        },
        {
          orderNumber: 'orderNumber 5',
          customer: 5,
          totalAmount: 0.03,
          vat: 0.83,
          totalAmountWithVat: 0.02,
          shippingCost: 0.03,
          shippingAddress: 'shippingAddress 5',
          orderAddress: 'orderAddress 5',
          orderEmail: 'orderEmail 5',
          orderDate: '2024-12-01T05:01:30.174Z',
          orderStatus: 'orderStatus 5',
          trackingNo: 'trackingNo 5',
          id: 2,
        },
      ],
      OrderDetails: [
        {
          orderNumber: 1,
          line: 1,
          product: 1,
          price: 0.87,
          quantity: 1,
          id: 69,
        },
        {
          orderNumber: 2,
          line: 2,
          product: 2,
          price: 0.15,
          quantity: 2,
          id: 56,
        },
        {
          orderNumber: 3,
          line: 3,
          product: 3,
          price: 0.32,
          quantity: 3,
          id: 66,
        },
        { orderNumber: 4, line: 4, product: 4, price: 0.5, quantity: 4, id: 1 },
        {
          orderNumber: 5,
          line: 5,
          product: 5,
          price: 0.83,
          quantity: 5,
          id: 86,
        },
      ],
      Payments: [
        {
          orderNumber: 1,
          amount: 0.01,
          paymentMethod: 'paymentMethod 1',
          paymentDate: '2023-10-30T07:02:00.392Z',
          paymentStatus: 'paymentStatus 1',
          id: 44,
        },
        {
          orderNumber: 2,
          amount: 0.85,
          paymentMethod: 'paymentMethod 2',
          paymentDate: '2023-07-03T00:45:20.347Z',
          paymentStatus: 'paymentStatus 2',
          id: 2,
        },
        {
          orderNumber: 3,
          amount: 0.94,
          paymentMethod: 'paymentMethod 3',
          paymentDate: '2025-03-01T01:36:16.224Z',
          paymentStatus: 'paymentStatus 3',
          id: 22,
        },
        {
          orderNumber: 4,
          amount: 0.17,
          paymentMethod: 'paymentMethod 4',
          paymentDate: '2023-07-08T08:32:33.263Z',
          paymentStatus: 'paymentStatus 4',
          id: 88,
        },
        {
          orderNumber: 5,
          amount: 0.25,
          paymentMethod: 'paymentMethod 5',
          paymentDate: '2025-03-11T22:23:49.668Z',
          paymentStatus: 'paymentStatus 5',
          id: 89,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 1,
          vendor: 1,
          rating: 0.37,
          reviewDetails: 'reviewDetails 1',
          date: '2024-05-23T22:01:10.759Z',
          id: 5,
        },
        {
          product: 2,
          customer: 2,
          vendor: 2,
          rating: 0.77,
          reviewDetails: 'reviewDetails 2',
          date: '2024-07-06T18:50:20.363Z',
          id: 97,
        },
        {
          product: 3,
          customer: 3,
          vendor: 3,
          rating: 0.79,
          reviewDetails: 'reviewDetails 3',
          date: '2024-10-15T08:53:48.820Z',
          id: 47,
        },
        {
          product: 4,
          customer: 4,
          vendor: 4,
          rating: 0.39,
          reviewDetails: 'reviewDetails 4',
          date: '2024-08-12T04:54:18.016Z',
          id: 74,
        },
        {
          product: 5,
          customer: 5,
          vendor: 5,
          rating: 0.12,
          reviewDetails: 'reviewDetails 5',
          date: '2025-03-26T07:14:43.653Z',
          id: 47,
        },
      ],
      SupportTickets: [
        {
          user: 1,
          customer: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2023-09-21T02:53:23.140Z',
          resolutionDate: '2023-10-08T23:11:57.474Z',
          id: 28,
        },
        {
          user: 2,
          customer: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2024-04-01T06:08:55.167Z',
          resolutionDate: '2023-08-28T14:26:41.713Z',
          id: 38,
        },
        {
          user: 3,
          customer: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2025-03-16T04:36:45.532Z',
          resolutionDate: '2024-11-16T16:15:06.515Z',
          id: 71,
        },
        {
          user: 4,
          customer: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2023-07-16T10:57:16.901Z',
          resolutionDate: '2023-05-18T15:26:51.545Z',
          id: 99,
        },
        {
          user: 5,
          customer: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2024-08-02T07:50:07.237Z',
          resolutionDate: '2024-07-16T20:56:10.214Z',
          id: 26,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('InventoryEntity', data.Inventory);
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductCategoriesEntity',
        data.ProductCategories,
      );
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('ShoppingCartEntity', data.ShoppingCart);
      await this.SeedResource('OrdersEntity', data.Orders);
      await this.SeedResource('OrderDetailsEntity', data.OrderDetails);
      await this.SeedResource('PaymentsEntity', data.Payments);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
